multiSelect/config/routes.rb
Rails.application.routes.draw do
  resources :authorbooks
  resources :books
  resources :authors

end

multiSelect/app/models/author.rb
class Author < ActiveRecord::Base
#attr_accessor :name
validates :name, :presence => true

has_many :authorbooks
accepts_nested_attributes_for :authorbooks
has_many :books, :through => :authorbooks



end

multiSelect/app/models/authorbook.rb
class Authorbook < ActiveRecord::Base

#attr_accessor :author_id, :book_id
belongs_to :book
belongs_to :author

end

multiSelect/app/models/book.rb
class Book < ActiveRecord::Base

#attr_accessor :name
validates :name, :presence => true
has_many :authorbooks
accepts_nested_attributes_for :authorbooks
has_many :authors, :through => :authorbooks
#accepts_nested_attributes_for :authorbooks
end

multiSelect/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

multiSelect/app/controllers/authorbooks_controller.rb
class AuthorbooksController < ApplicationController
  before_action :set_authorbook, only: [:show, :edit, :update, :destroy]

  # GET /authorbooks
  # GET /authorbooks.json
  def index
    @authorbooks = Authorbook.all
  end

  # GET /authorbooks/1
  # GET /authorbooks/1.json
  def show
  end

  # GET /authorbooks/new
  def new
    @authorbook = Authorbook.new
  end

  # GET /authorbooks/1/edit
  def edit
  end

  # POST /authorbooks
  # POST /authorbooks.json
  def create
    @authorbook = Authorbook.new(authorbook_params)

    respond_to do |format|
      if @authorbook.save
        format.html { redirect_to @authorbook, notice: 'Authorbook was successfully created.' }
        format.json { render :show, status: :created, location: @authorbook }
      else
        format.html { render :new }
        format.json { render json: @authorbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authorbooks/1
  # PATCH/PUT /authorbooks/1.json
  def update
    respond_to do |format|
      if @authorbook.update(authorbook_params)
        format.html { redirect_to @authorbook, notice: 'Authorbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @authorbook }
      else
        format.html { render :edit }
        format.json { render json: @authorbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorbooks/1
  # DELETE /authorbooks/1.json
  def destroy
    @authorbook.destroy
    respond_to do |format|
      format.html { redirect_to authorbooks_url, notice: 'Authorbook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authorbook
      @authorbook = Authorbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def authorbook_params
      params.require(:authorbook).permit(:author_id, :book_id)
    end
end

multiSelect/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
    get_books
    respond_to do |format|
    format.html
    format.json { render json: @author }
  end

  end

  # GET /authors/1/edit
  def edit
    get_books
  end
  # POST /authors
  # POST /authors.json
  def create

    @author = Author.new(author_params)
    params[:books][:id].each do |book|
      if !book.empty?
        @author.authorbooks.build(:book_id => book)
      end
    end

    #binding.pry
    respond_to do |format|
      if @author.save

       # author_id = @author.id
       # create_params[:book_id].each do |bookid|
       #  @authorbooks = Authorbook.new(author_id: author_id, book_id: bookid)
       #  @authorbooks.save
       # end

        # author_id = @author.id
        # author_book = params[:book].split(',')
        # ab_ids = Book.where(name: author_book).pluck('id')
        # ab_ids.each do |id|
        # author_books = Authorbook.new(author_id: author_id, book_id: id)
        # author_books.save
 
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    #binding.pry
    respond_to do |format|
      if @author.update(author_params)
        
        @author.books = []
        params[:books][:id].each do |book|
          if !book.empty?
            @author.books << Book.find(book)
          end
        end
        
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name,:authorbooks_attributes => [:id,:book_ids => []])
      
    end

    def get_books
      @all_books = Book.all
      @author_book = @author.authorbooks.build
    end

    # def create_params
    #   params.require(:authorbooks).permit(:author_id,book_id: [])
    # end
end

multiSelect/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name)
    end
end

multiSelect/app/helpers/application_helper.rb
module ApplicationHelper
end

multiSelect/app/helpers/authorbooks_helper.rb
module AuthorbooksHelper
end

multiSelect/app/helpers/authors_helper.rb
module AuthorsHelper
end

multiSelect/app/helpers/books_helper.rb
module BooksHelper
end

multiSelect/app/views/authorbooks/_form.html.erb
<%= form_for(@authorbook) do |f| %>
  <% if @authorbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authorbook.errors.count, "error") %> prohibited this authorbook from being saved:</h2>

      <ul>
      <% @authorbook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.number_field :author_id %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br>
    <%= f.number_field :book_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

multiSelect/app/views/authorbooks/edit.html.erb
<h1>Editing Authorbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @authorbook %> |
<%= link_to 'Back', authorbooks_path %>

multiSelect/app/views/authorbooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authorbooks</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authorbooks.each do |authorbook| %>
      <tr>
        <td><%= authorbook.author_id %></td>
        <td><%= authorbook.book_id %></td>
        <td><%= link_to 'Show', authorbook %></td>
        <td><%= link_to 'Edit', edit_authorbook_path(authorbook) %></td>
        <td><%= link_to 'Destroy', authorbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authorbook', new_authorbook_path %>

multiSelect/app/views/authorbooks/new.html.erb
<h1>New Authorbook</h1>

<%= render 'form' %>

<%= link_to 'Back', authorbooks_path %>

multiSelect/app/views/authorbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @authorbook.author_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @authorbook.book_id %>
</p>

<%= link_to 'Edit', edit_authorbook_path(@authorbook) %> |
<%= link_to 'Back', authorbooks_path %>

multiSelect/app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <%= fields_for(@author_book) do |ab| %>
  <div class="field">
    <%= ab.label "All Books" %><br>
    <%= collection_select(:books, :id, @all_books, :id, :name, {:selected => @author.books.map(&:id)}, {multiple: true}) %>
  </div>
  <% end %>




<%# <%= ab.collection_select(:book_id, Book.all, :id, :name,{include_blank: false, :include_hidden => false, :selected => @author.authorbooks.map(&:id)},
                              {:multiple => true})%>

<%#<%= collection_select(:ingredient, :supplier_ids, 
              Supplier.all(:order=>"name ASC"), 
              :id, :name, {:selected => @ingredient.supplier_ids, :include_blank => true}, {:multiple => true}) %>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script type="text/javascript">
$(document).ready(function() {
  $("#books_id").select2({
    placeholder: "Select Books",
    width: '28%',
    allowClear: true,
    tags: true

  });
});
</script> 

multiSelect/app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

multiSelect/app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

multiSelect/app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

multiSelect/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<% if @author.books.present? %>
	<h4>List of Books</h4>
	<% @author.books.each do |book| %>
	   <p><%= link_to book.name, book %></p>
	<% end %>   
<% else %>
	<h4>No books for this author yet</h4>
<% end %>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

multiSelect/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

multiSelect/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

multiSelect/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

multiSelect/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

multiSelect/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<% if @book.authors.present? %>
	<h4>List of Books</h4>
	<% @book.authors.each do |author| %>
	   <p><%= link_to author.name, author %></p>
	<% end %>   
<% else %>
	<h4>No Author for this book yet</h4>
<% end %>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

multiSelect/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MultiSelect</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>